### PR TITLE
Define address for easier address change

### PR DESCRIPTION
**Pull request by muhammadrefa**
Define address in `bno055.h` so no need to change address in function `bno055_readData()` and `bno055_writeData()` inside `bno055_stm32.h`

### CODE REVIEW

**Comment by arrowcircle** [comment]
Hi! Thanks for the interest in this lib. Could you please tell more about this change? It looks like rename of the address define for me.

**Comment by muhammadrefa** [comment]
If you have different BNO055 address (it's 0x28 as default in your library), you need to change addresses inside bno055_readData() and bno055_writeData() functions

In my pull request, you only need to change address in bno055.h if you have different address so you don't have to mess with other function(s)

**Comment by arrowcircle** [comment]
But there is already `BNO055_I2C_ADDR_LO ` define here. Could you please explain the difference?

**Comment by muhammadrefa** [comment]
In your code, you use `BNO055_I2C_ADDR_LO` as BNO055 address. I'm using `BNO055_I2C_ADDR_HI` for my IMU module. It takes time for me to realize the wrong address in my code (that use your library), and some mistakes when change the address (I've changed the address for `bno055_readData()` but not for `bno055_writeData()`)

In my code, I define the I2C address to `BNO055_I2C_ADDR` (line 19) and use it on `bno055_readData()` (line 97) and `bno055_writeData()` (line 35) functions so you only need to change the address in `BNO055_I2C_ADDR` and not have to mess with the other functions

**Comment by arrowcircle** [comment]
@Oliv4945 any ideas if proposed change is usefull

@muhammadrefa Could you please separate quaternion code to separate branch? This is different thing so it's better not to mess everything in one place. Also, please check travis CI checks.

**Comment by muhammadrefa** [comment]
Okay I'll fix it

**Comment by muhammadrefa** [comment]
Updated the README file and add an explanation about address setting (my pull request)
Sorry if I'm not doing it right

**Comment by arrowcircle** [comment]
Readme looks ok, but I still dont get why we need these changes.

Can we make i2c address defined as lo and add example of how to redefine it? Because I prefer "convention over configuration" way. So if something is working by default we dont need to define it explicitely in code. What do you thing?

**Comment by muhammadrefa** [comment]
The problem is I can't get the code working out of the box. I need to change the i2c address because my module has 0x29 (hi) as the address. So I need to change the address in writeData and readData function

Yes we can add an example of how to redefine it. This pull request makes address change easier because you only need to change address in one place rather than in two places

**Comment by arrowcircle** [comment]
Ok, I got it. Could you please uncomment i2c?

**Comment by Oliv4945** [comment]
Hi,

It think this change is great, to avoid all this hassle I set ``BNO055_I2C_ADDR_LO` to `0x29` in my code which is kinda dirty.
But before merging it, @muhammadrefa, you should rebase your changes to have cleaner git history, otherwise it will be confusing for others

**Comment by arrowcircle** [comment]
@Oliv4945 We can "sqash and merge" commits right here in the pull request, isn't it?

**Comment by arrowcircle** [comment]
@muhammadrefa Merged!

**Pull request merged**
