### PR TITLE
Add "extern c" for cpp use

### PR DESCRIPTION
**Pull request by Oliv4945**
Thank you for the library, works out of the box !
I will try to help to add some parameters and maybe interruptions

### CODE REVIEW

**Comment by arrowcircle** [comment]
Please keep linter fine :)

**Comment by Oliv4945** [comment]
Oops, sorry. Corrected

**Comment by arrowcircle** [comment]
Thanks for the pull request. Merging now.

**Comment by arrowcircle** [comment]
@Oliv4945 BTW, do you have any thought about how to wrap this module into c++ class?
After wrapping it into class, it's possible to add proper automatic testing and examples of great code with hardware abstractions.

**Comment by Oliv4945** [comment]
I depend if you want to maintain both C and C++ interface. In my opinion it is cleaner to provide only C++ code but has we discuss about embedded code you will find lot of points of views :)

First step is obviously a wrapper, I might do one one day but I have other "functional" PR to do before

**Comment by arrowcircle** [comment]
@Oliv4945 Thing is I am not so experienced in embedded development, but for stm32 it's tricky to add C++ implementation of the class. I think C implementation is first priority, and C++ can be added as a separate code.
Also, do you have any ideas about how to make a package from this code in C or C++? In Rust there is cargo tool to build and manage dependencies. Any ideas about it?

**Comment by Oliv4945** [comment]
Agreed, having a complete C implementation is better than partial C and C++ :) That is why I am working on a PR to save calibration values, it will avoid re-calibration every power-on.

C and C++ are old languages which have not been designed for dependency management; you have to use third party tools.  [This article](https://foonathan.net/blog/2016/07/07/cmake-dependency-handling.html) introduction is a nice summary: difficult to do as their is so many tools :) However CMake is doing a nice job for that

**Pull request merged**
